"""
👩‍💻 Running Agent generated code in Daytona

This example shows how to run code generated by an Agno Agent using Daytona.

1. Get your Daytona API key and API URL: https://app.daytona.io/dashboard/keys
2. Set the API key and API URL as environment variables:
    export DAYTONA_API_KEY=<your_api_key>
    export DAYTONA_API_URL=<your_api_url>

pip install agno anthropic daytona_sdk
"""

import os
from textwrap import dedent

from agno.agent import Agent
from agno.models.anthropic import Claude
from agno.run.response import RunResponse
from daytona_sdk import Daytona, DaytonaConfig

DAYTONA_API_KEY = os.getenv("DAYTONA_API_KEY")
DAYTONA_API_URL = os.getenv("DAYTONA_API_URL")
DAYTONA_CONFIG = DaytonaConfig(api_key=DAYTONA_API_KEY, api_url=DAYTONA_API_URL)


def run_code_in_daytona(code: str) -> None:
    """Run the given code in Daytona and print the result."""
    daytona = Daytona(DAYTONA_CONFIG)
    sandbox = daytona.create()
    response = sandbox.process.code_run(code)

    if response.exit_code != 0:
        print(f"Error: {response.exit_code} {response.result}")
    else:
        print("--------------------------------")
        print("👩‍💻 Daytona code execution result:")
        print("--------------------------------")
        print(response.result)


# Initialize the Agent we will use to generate the code
coding_agent = Agent(
    model=Claude(id="claude-3-7-sonnet-latest"),
    instructions=dedent("""
    You are a skilled Python developer. You are given programming tasks and you need to complete them.
    Always respond just with the code to complete the task. Do not include any other text. Do not use markdown.
    Make sure the code is valid Python code that can be executed.
    """),
)

# Run the Agent to generate the code
response: RunResponse = coding_agent.run(
    "Write a Python script to check how many 'r' are in the word 'strawberry' and print a verbose result."
)

# Run the generated code in Daytona
run_code_in_daytona(response.content)
