"""
👩‍💻 Running Agent generated code in E2B

This example shows how to run code generated by an Agno Agent using E2B.

1. Get your E2B API key: https://e2b.dev/dashboard?tab=keys
2. Export the API key as an environment variable:
    export E2B_API_KEY=<your_api_key>

pip install agno anthropic e2b-code-interpreter
"""

import os
from textwrap import dedent

from agno.agent import Agent
from agno.models.anthropic import Claude
from agno.run.response import RunResponse
from e2b_code_interpreter import Sandbox

E2B_API_KEY = os.getenv("E2B_API_KEY")


def run_code_in_e2b(code: str) -> None:
    """Run the given code in E2B and print the result."""
    with Sandbox() as sandbox:
        execution = sandbox.run_code(code)
        result = execution.logs.stdout[0]
        print("--------------------------------")
        print("👩‍💻 E2B code execution result:")
        print("--------------------------------")
        print(result)


# Initialize the Agent we will use to generate the code
coding_agent = Agent(
    model=Claude(id="claude-3-7-sonnet-latest"),
    instructions=dedent("""
    You are a skilled Python developer. You are given programming tasks and you need to complete them.
    Always respond just with the code to complete the task. Do not include any other text. Do not use markdown.
    Make sure the code is valid Python code that can be executed.
    """),
)

# Run the Agent to generate the code
response: RunResponse = coding_agent.run(
    "Write a Python script to check how many 'r' are in the word 'strawberry' and print a verbose result."
)

# Run the generated code in E2B
run_code_in_e2b(response.content)
